name: 'redshift_seq_demo'
version: '1.0'
config-version: 2

profile: 'redshift_profile'

# Automatically create sequences for all sources at run start
on-run-start:
  - "{{ create_sequences_for_sources('staging') }}"

models:
  redshift_seq_demo:
    staging:
      +materialized: incremental
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
