# dbt_project.yml
name: my_new_project
version: "1.0.0"
config-version: 2
profile: default
 
models:
  my_new_project:     # match project name above
    Consumption:          # all staging layer models
      +schema: consumption
      +materialized: table
    Integration_stage:      # intermediate transformations
      +schema: Integration_stage
      +materialized: table
    Integration_target:      # intermediate transformations
      +schema: Integration_target
      +materialized: table


   