# dbt_project.yml
name: Deckers
version: "1.0.0"
config-version: 2
profile: default
 
models:
  Deckers:
    +schema: testing     # default schema under the connected DB
    staging:
      +schema: consumption
    
 