{{ config(materialized = 'table') }} with 
ap_invoices_all as (
  select 
    * 
  from 
    {{ ref("ap_invoices_all") }}
), 
ap_holds_all as (
  select 
    * 
  from 
    {{ ref("ap_holds_all") }}
), 
ap_invoice_lines_all as (
  select 
    * 
  from 
    {{ ref("ap_invoice_lines_all") }}
), 
po_headers_all as (
  select 
    * 
  from 
    {{ ref("po_headers_all") }}
), 
hz_parties as (
  select 
    * 
  from 
    {{ ref("hz_parties") }}
), 
hz_party_sites as (
  select 
    * 
  from 
    {{ ref("hz_party_sites") }}
), 
ap_hold_codes as (
  select 
    * 
  from 
    {{ ref("ap_hold_codes") }}
), 
gl_ledgers as (
  select 
    * 
  from 
    {{ ref("gl_ledgers") }}
), 
ap_lookup_codes as (
  select 
    * 
  from 
    {{ ref("ap_lookup_codes") }}
), 
ct_ap_holds_f_stg as (
  SELECT COALESCE(CAST(APHOLDS_F_JOIN_A.VENDOR_ID AS VARCHAR), '0') || '~' || COALESCE(CAST(APHOLDS_F_JOIN_A.VENDOR_SITE_ID AS VARCHAR), '0') AS SUPPLIER_ID, CAST(APHOLDS_F_JOIN_A.SET_OF_BOOKS_ID AS VARCHAR) AS LEDGER_ID, CAST(APHOLDS_F_JOIN_A.ORG_ID_1 AS VARCHAR) AS BU_ID, CAST(APHOLDS_F_JOIN_A.LEGAL_ENTITY_ID AS VARCHAR) AS LEGAL_ENTITY_ID, CAST(COALESCE(APHOLDS_F_JOIN_A.ACCTS_PAY_CODE_COMBINATION_ID, 0) AS VARCHAR) AS GLCC_ID, CAST(APHOLDS_F_JOIN_A.ORG_ID AS VARCHAR) AS ORG_ID, CAST(TO_CHAR(APHOLDS_F_JOIN_A.INVOICE_DATE, 'YYYYMMDD') AS INT) AS INVOICE_DT_ID, CAST(TO_CHAR(APHOLDS_F_JOIN_A.HOLD_DATE, 'YYYYMMDD') AS INT) AS HOLD_DT_ID, CAST(TO_CHAR(APHOLDS_F_JOIN_A.GL_DATE, 'YYYYMMDD') AS INT) AS ACCOUNTING_DT_ID, CAST(COALESCE(APHOLDS_F_JOIN_A.INVENTORY_ITEM_ID, 0) AS VARCHAR) AS PRODUCT_ID, NULL AS SUPPLIER_CONTACT, TO_CHAR(APHOLDS_F_JOIN_A.INVOICE_DATE, 'MON-YY') AS PERIOD_NAME, EXTRACT(YEAR FROM APHOLDS_F_JOIN_A.INVOICE_DATE) AS PERIOD_YEAR, EXTRACT(MONTH FROM APHOLDS_F_JOIN_A.INVOICE_DATE) AS PERIOD_NUM, APHOLDS_F_JOIN_A.NAME AS LEDGER_NAME, APHOLDS_F_JOIN_A.INVOICE_ID, APHOLDS_F_JOIN_A.INVOICE_NUM, APHOLDS_F_JOIN_A.DESCRIPTION AS INVOICE_DESC, APHOLDS_F_JOIN_A.LINE_NUMBER AS INVOICE_LINE_NUM, APHOLDS_F_JOIN_A.HOLD_LOOKUP_CODE, APHOLDS_F_JOIN_A.HOLD_REASON, APHOLDS_F_JOIN_A.HOLD_DATE AS HOLD_DT, APHOLDS_F_JOIN_A.HOLD_DETAILS, APHOLDS_F_JOIN_A.GL_DATE AS ACCOUNTING_DT, APHOLDS_F_JOIN_A.INVOICE_DATE AS INVOICE_DT, APHOLDS_F_JOIN_A.RELEASE_LOOKUP_CODE, APHOLDS_F_JOIN_A.RELEASE_REASON, APHOLDS_F_JOIN_A.HOLD_TYPE_1 AS RELEASE_TYPE, APHOLDS_F_JOIN_A.SEGMENT1 AS IDENTIFYING_PO, APHOLDS_F_JOIN_A.HOLD_TYPE, APHOLDS_F_JOIN_A.SOURCE AS INVOICE_SOURCE_NAME, APHOLDS_F_JOIN_A.APPROVAL_STATUS AS VALIDATION_STATUS, APHOLDS_F_JOIN_A.WFAPPROVAL_STATUS AS INV_WFAPPROVAL_STATUS, APHOLDS_F_JOIN_A.INVOICE_CURRENCY_CODE AS INV_CURR_CODE, APHOLDS_F_JOIN_A.CURRENCY_CODE AS LEDGER_CURR_CODE, APHOLDS_F_JOIN_A.DISPLAYED_FIELD AS HOLD_NAME, APHOLDS_F_JOIN_A.REQUESTER_ID AS REQUESTER_ID, APHOLDS_F_JOIN_A.WF_STATUS AS HOLD_WFAPPROVAL_STATUS, APHOLDS_F_JOIN_A.DISPLAYED_FIELD_1 AS HOLD_RELEASE_NAME, NULL AS HOLD_CNT, APHOLDS_F_JOIN_A.INVOICE_AMOUNT, APHOLDS_F_JOIN_A.INVOICE_AMOUNT AS INVOICE_AMOUNT_USD, 0 AS CONV_RATE_TO_USD, NULL AS CONV_RATE_TYPE, APHOLDS_F_JOIN_A.CREATION_DATE AS CREATION_DT, APHOLDS_F_JOIN_A.LAST_UPDATE_DATE AS LAST_UPDATE_DT, APHOLDS_F_JOIN_A.CREATED_BY, APHOLDS_F_JOIN_A.LAST_UPDATED_BY, CAST(APHOLDS_F_JOIN_A.INVOICE_ID AS VARCHAR) || '~' || CAST(APHOLDS_F_JOIN_A.LINE_NUMBER AS VARCHAR) || '~' || CAST(APHOLDS_F_JOIN_A.HOLD_ID AS VARCHAR) || '~' || COALESCE(CAST(APHOLDS_F_JOIN_A.HOLD_REASON AS VARCHAR), '') AS INTEGRATION_ID, 1000 AS DATASOURCE_NUM_ID, 'N' AS DELETE_FLAG FROM ( SELECT INVOICES_ALL.INVOICE_ID, INVOICES_ALL.INVOICE_NUM, INVOICES_ALL.SET_OF_BOOKS_ID, INVOICES_ALL.INVOICE_CURRENCY_CODE, INVOICES_ALL.INVOICE_AMOUNT, INVOICES_ALL.VENDOR_ID, INVOICES_ALL.VENDOR_SITE_ID, INVOICES_ALL.INVOICE_DATE, INVOICES_ALL.SOURCE, INVOICES_ALL.DESCRIPTION, INVOICES_ALL.ACCTS_PAY_CODE_COMBINATION_ID, INVOICES_ALL.APPROVAL_STATUS, INVOICES_ALL.ORG_ID, INVOICES_ALL.GL_DATE, INVOICES_ALL.WFAPPROVAL_STATUS, INVOICES_ALL.REQUESTER_ID, INVOICES_ALL.LEGAL_ENTITY_ID, HOLDS_ALL.HOLD_LOOKUP_CODE, HOLDS_ALL.LAST_UPDATE_DATE, HOLDS_ALL.LAST_UPDATED_BY, HOLDS_ALL.HOLD_DATE, HOLDS_ALL.HOLD_REASON, HOLDS_ALL.RELEASE_LOOKUP_CODE, HOLDS_ALL.RELEASE_REASON, HOLDS_ALL.CREATION_DATE, HOLDS_ALL.CREATED_BY, HOLDS_ALL.ORG_ID AS ORG_ID_1, HOLDS_ALL.HOLD_DETAILS, HOLDS_ALL.HOLD_ID, HOLDS_ALL.WF_STATUS, INVOICE_LINES_ALL.LINE_NUMBER, INVOICE_LINES_ALL.INVENTORY_ITEM_ID, HOLD_CODES.HOLD_TYPE, LOOKUP_CODES.DISPLAYED_FIELD, GL_LEDGERS.NAME, GL_LEDGERS.CURRENCY_CODE, PO_HEADERS_ALL.SEGMENT1, HOLD_CODES1.HOLD_TYPE AS HOLD_TYPE_1, LOOKUP_CODES1.DISPLAYED_FIELD AS DISPLAYED_FIELD_1 FROM AP_INVOICES_ALL INVOICES_ALL JOIN AP_HOLDS_ALL HOLDS_ALL ON HOLDS_ALL.INVOICE_ID = INVOICES_ALL.INVOICE_ID JOIN AP_INVOICE_LINES_ALL INVOICE_LINES_ALL ON INVOICE_LINES_ALL.INVOICE_ID = INVOICES_ALL.INVOICE_ID LEFT JOIN PO_HEADERS_ALL PO_HEADERS_ALL ON INVOICES_ALL.PO_HEADER_ID = PO_HEADERS_ALL.PO_HEADER_ID LEFT JOIN HZ_PARTIES HZ_PARTIES ON INVOICES_ALL.PARTY_ID = HZ_PARTIES.PARTY_ID LEFT JOIN HZ_PARTY_SITES HZ_PARTY_SITES ON INVOICES_ALL.PARTY_SITE_ID = HZ_PARTY_SITES.PARTY_SITE_ID JOIN AP_HOLD_CODES HOLD_CODES ON HOLDS_ALL.HOLD_LOOKUP_CODE = HOLD_CODES.HOLD_LOOKUP_CODE LEFT JOIN AP_HOLD_CODES HOLD_CODES1 ON HOLDS_ALL.RELEASE_LOOKUP_CODE = HOLD_CODES1.HOLD_LOOKUP_CODE JOIN GL_LEDGERS GL_LEDGERS ON GL_LEDGERS.LEDGER_ID = INVOICES_ALL.SET_OF_BOOKS_ID JOIN AP_LOOKUP_CODES LOOKUP_CODES ON HOLDS_ALL.HOLD_LOOKUP_CODE = LOOKUP_CODES.LOOKUP_CODE AND LOOKUP_CODES.LOOKUP_TYPE = 'HOLD CODE' LEFT JOIN AP_LOOKUP_CODES LOOKUP_CODES1 ON HOLDS_ALL.RELEASE_LOOKUP_CODE = LOOKUP_CODES1.LOOKUP_CODE AND LOOKUP_CODES1.LOOKUP_TYPE = 'HOLD CODE' WHERE HOLDS_ALL.last_update_date >= CAST('2025-09-01' AS DATE) OR INVOICES_ALL.last_update_date >= CAST('2025-09-01' AS DATE) OR INVOICE_LINES_ALL.last_update_date >= CAST('2025-09-01' AS DATE) ) APHOLDS_F_JOIN_A

)
    select * from ct_ap_holds_f_stg

