{{ config(materialized='table') }}

    with
    invoice_date as (
    select * from {{ ref("invoice_date") }}
),
payment_date as (
    select * from {{ ref("payment_date") }}
),
gl_date as (
    select * from {{ ref("gl_date") }}
),
accounting_date as (
    select * from {{ ref("accounting_date") }}
),
ap_invoice_payments_all as (
    select * from {{ ref("ap_invoice_payments_all") }}
),
ap_invoices_all as (
    select * from {{ ref("ap_invoices_all") }}
),
ap_checks_all as (
    select * from {{ ref("ap_checks_all") }}
),
ap_payment_schedules_all as (
    select * from {{ ref("ap_payment_schedules_all") }}
),
ap_lookup_codes as (
    select * from {{ ref("ap_lookup_codes") }}
),
ce_payment_documents as (
    select * from {{ ref("ce_payment_documents") }}
),
iby_payments_all as (
    select * from {{ ref("iby_payments_all") }}
),
ap_terms_tl as (
    select * from {{ ref("ap_terms_tl") }}
),
gl_ledgers as (
    select * from {{ ref("gl_ledgers") }}
),
gl_code_combinations as (
    select * from {{ ref("gl_code_combinations") }}
),
iby_payment_methods_tl as (
    select * from {{ ref("iby_payment_methods_tl") }}
),
fnd_lookup_values as (
    select * from {{ ref("fnd_lookup_values") }}
),
ct_ap_payments_f_stg as (
    SELECT COALESCE(CAST(APPAYMENTS_F_JOIN_A.VENDOR_ID AS VARCHAR), '0') || '~' || COALESCE(CAST(APPAYMENTS_F_JOIN_A.VENDOR_SITE_ID AS VARCHAR), '0') AS SUPPLIER_ID, CAST(COALESCE(APPAYMENTS_F_JOIN_A.SET_OF_BOOKS_ID, 0) AS VARCHAR) AS LEDGER_ID, CAST(COALESCE(APPAYMENTS_F_JOIN_A.ORG_ID, 0) AS VARCHAR) AS BU_ID, CAST(COALESCE(APPAYMENTS_F_JOIN_A.LEGAL_ENTITY_ID, 0) AS VARCHAR) AS LEGAL_ENTITY_ID, CAST(COALESCE(APPAYMENTS_F_JOIN_A.ACCTS_PAY_CODE_COMBINATION_ID, 0) AS VARCHAR) AS GLCC_ID, CAST(APPAYMENTS_F_JOIN_A.ORG_ID AS VARCHAR) AS ORG_ID, COALESCE(CAST(EXTRACT(YEAR FROM invoice_date) * 10000 + EXTRACT(MONTH FROM invoice_date) * 100 + EXTRACT(DAY FROM invoice_date) AS BIGINT), 0) AS INVOICE_DT_ID, COALESCE(CAST(EXTRACT(YEAR FROM payment_date) * 10000 + EXTRACT(MONTH FROM payment_date) * 100 + EXTRACT(DAY FROM payment_date) AS BIGINT), 0) AS PAYMENT_DT_ID, CAST(EXTRACT(YEAR FROM gl_date) * 10000 + EXTRACT(MONTH FROM gl_date) * 100 + EXTRACT(DAY FROM gl_date) AS BIGINT) AS GL_DT_ID, CAST(EXTRACT(YEAR FROM accounting_date) * 10000 + EXTRACT(MONTH FROM accounting_date) * 100 + EXTRACT(DAY FROM accounting_date) AS BIGINT) AS ACCOUNTING_DT_ID, TO_CHAR(APPAYMENTS_F_JOIN_A.ACCOUNTING_DATE, 'Mon-YY') AS PERIOD_NAME, EXTRACT(YEAR FROM accounting_date) AS PERIOD_YEAR, EXTRACT(MONTH FROM accounting_date) AS PERIOD_NUM, NULL AS SUPPLIER_CONTACT, APPAYMENTS_F_JOIN_A.NAME AS LEDGER_NAME, APPAYMENTS_F_JOIN_A.CHECK_ID AS CHECK_ID, APPAYMENTS_F_JOIN_A.CHECK_NUMBER AS CHECK_NUM, APPAYMENTS_F_JOIN_A.CHECK_VOUCHER_NUM AS CHECK_VOUCHER_NUM, APPAYMENTS_F_JOIN_A.CHECK_DATE AS CHECK_DT, APPAYMENTS_F_JOIN_A.PAYMENT_CURRENCY_CODE AS PAYMENT_CURR_CODE, APPAYMENTS_F_JOIN_A.CURRENCY_CODE AS LEDGER_CURR_CODE, APPAYMENTS_F_JOIN_A.INVOICE_DATE AS GL_DT, APPAYMENTS_F_JOIN_A.ACCOUNTING_DATE AS ACCOUNTING_DT, APPAYMENTS_F_JOIN_A.INVOICE_DATE AS INVOICE_DT, APPAYMENTS_F_JOIN_A.INVOICE_ID AS INVOICE_ID, APPAYMENTS_F_JOIN_A.INVOICE_NUM AS INVOICE_NUM, APPAYMENTS_F_JOIN_A.INVOICE_CURRENCY_CODE AS INV_CURR_CODE, APPAYMENTS_F_JOIN_A.DUE_DATE AS PAYMENT_DUE_DT, '-' AS PO_NUMBER, APPAYMENTS_F_JOIN_A.PAYEE_NAME AS PAYEE_NAME, APPAYMENTS_F_JOIN_A.PAYEE_SUPPLIER_SITE_NAME AS PAYEE_SITE_NAME, APPAYMENTS_F_JOIN_A.DISPLAYED_FIELD AS CHECK_STATUS, CASE WHEN APPAYMENTS_F_JOIN_A.PAYMENT_STATUS_FLAG = 'Y' THEN 'Paid' WHEN APPAYMENTS_F_JOIN_A.PAYMENT_STATUS_FLAG = 'N' THEN 'Not Paid' WHEN APPAYMENTS_F_JOIN_A.PAYMENT_STATUS_FLAG = 'P' THEN 'Partially paid' ELSE NULL END AS PAYMENT_STATUS, APPAYMENTS_F_JOIN_A.PAYMENT_STATUS_FLAG AS PAYMENT_STATUS_FLAG, APPAYMENTS_F_JOIN_A.STOPPED_DATE AS PAYMENT_STOPPED_DT, APPAYMENTS_F_JOIN_A.VOID_DATE AS PAYMENT_VOID_DT, APPAYMENTS_F_JOIN_A.RELEASED_DATE AS PAYMENT_RELEASED_DT, APPAYMENTS_F_JOIN_A.EXT_BANK_ACCOUNT_NUMBER AS REMIT_TO_BANK_ACCOUNT_NO, APPAYMENTS_F_JOIN_A.EXT_BANK_NAME AS REMIT_TO_BANK_NAME, APPAYMENTS_F_JOIN_A.EXT_BANK_BRANCH_NAME AS REMIT_TO_BRANCH_NAME, APPAYMENTS_F_JOIN_A.PAYEE_ADDRESS_CONCAT AS REMIT_TO_ADDRESS, APPAYMENTS_F_JOIN_A.BENEFICIARY_NAME AS BENEFICIARY_NAME, APPAYMENTS_F_JOIN_A.PAYMENT_METHOD_NAME AS PAYMENT_METHOD_NAME, APPAYMENTS_F_JOIN_A.CANCELLED_DATE AS CANCELLED_DT, APPAYMENTS_F_JOIN_A.CANCELLED_BY AS CANCELLED_BY, APPAYMENTS_F_JOIN_A.ACCRUAL_POSTED_FLAG AS ACCRUAL_POSTED_FLAG, APPAYMENTS_F_JOIN_A.CASH_POSTED_FLAG AS CASH_POSTED_FLAG, APPAYMENTS_F_JOIN_A.POSTED_FLAG AS POSTED_FLAG, COALESCE(APPAYMENTS_F_JOIN_A.INVOICE_AMOUNT, 0) AS INVOICE_AMOUNT, COALESCE(APPAYMENTS_F_JOIN_A.AMOUNT, 0) AS CHECK_AMOUNT, COALESCE(APPAYMENTS_F_JOIN_A.AMOUNT_1, 0) AS PAYMENT_AMOUNT, 0 AS INVOICE_AMOUNT_USD, 0 AS CHECK_AMOUNT_USD, 0 AS PAYMENT_AMOUNT_USD, 0 AS CONV_PYMT_RATE_TO_USD, NULL AS CONV_PYMT_RATE_TYPE, 0 AS CONV_INV_RATE_TO_USD, NULL AS CONV_INV_RATE_TYPE, APPAYMENTS_F_JOIN_A.CREATION_DATE AS CREATION_DT, APPAYMENTS_F_JOIN_A.LAST_UPDATE_DATE AS LAST_UPDATE_DT, APPAYMENTS_F_JOIN_A.CREATED_BY AS CREATED_BY, APPAYMENTS_F_JOIN_A.LAST_UPDATED_BY AS LAST_UPDATED_BY, COALESCE(APPAYMENTS_F_JOIN_A.INVOICE_PAYMENT_ID, 0)::VARCHAR || '~' || COALESCE(APPAYMENTS_F_JOIN_A.CHECK_ID, 0)::VARCHAR || '~' || COALESCE(APPAYMENTS_F_JOIN_A.PAYMENT_ID, 0)::VARCHAR AS INTEGRATION_ID, 1000 AS DATASOURCE_NUM_ID, 'N' AS DELETE_FLAG, APPAYMENTS_F_JOIN_A.MEANING AS PAYMENT_TYPE, APPAYMENTS_F_JOIN_A.PAYMENT_DATE AS PAYMENT_DATE FROM ( SELECT CHECKS_ALL.AMOUNT, CHECKS_ALL.CHECK_DATE, CHECKS_ALL.CHECK_ID, CHECKS_ALL.CHECK_NUMBER, CHECKS_ALL.CHECK_VOUCHER_NUM, CHECKS_ALL.VOID_DATE, CHECKS_ALL.VENDOR_ID, CHECKS_ALL.VENDOR_SITE_ID, CHECKS_ALL.RELEASED_DATE, CHECKS_ALL.STOPPED_DATE, INVOICE_PAYMENTS_ALL.ACCOUNTING_DATE, INVOICE_PAYMENTS_ALL.ACCRUAL_POSTED_FLAG, INVOICE_PAYMENTS_ALL.AMOUNT AS AMOUNT_1, INVOICE_PAYMENTS_ALL.CASH_POSTED_FLAG, INVOICE_PAYMENTS_ALL.INVOICE_PAYMENT_ID, INVOICE_PAYMENTS_ALL.LAST_UPDATED_BY, INVOICE_PAYMENTS_ALL.LAST_UPDATE_DATE, INVOICE_PAYMENTS_ALL.POSTED_FLAG, INVOICE_PAYMENTS_ALL.SET_OF_BOOKS_ID, INVOICE_PAYMENTS_ALL.CREATED_BY, INVOICE_PAYMENTS_ALL.CREATION_DATE, INVOICE_PAYMENTS_ALL.ORG_ID, INVOICES_ALL.INVOICE_ID, INVOICES_ALL.INVOICE_NUM, INVOICES_ALL.INVOICE_CURRENCY_CODE, INVOICES_ALL.INVOICE_AMOUNT, INVOICES_ALL.INVOICE_DATE, INVOICES_ALL.ACCTS_PAY_CODE_COMBINATION_ID, INVOICES_ALL.CANCELLED_DATE, INVOICES_ALL.CANCELLED_BY, INVOICES_ALL.GL_DATE, PAYMENT_SCHEDULES_ALL.DUE_DATE, PAYMENT_SCHEDULES_ALL.PAYMENT_STATUS_FLAG, LOOKUP_CODES.DISPLAYED_FIELD, IBY_PAYMENTS_ALL.PAYMENT_ID, IBY_PAYMENTS_ALL.PAYMENT_CURRENCY_CODE, CHECKS_ALL.LEGAL_ENTITY_ID, IBY_PAYMENTS_ALL.PAYMENT_DATE, IBY_PAYMENTS_ALL.EXT_BANK_ACCOUNT_NUMBER, IBY_PAYMENTS_ALL.PAYEE_NAME, IBY_PAYMENTS_ALL.EXT_BANK_NAME, IBY_PAYMENTS_ALL.EXT_BANK_BRANCH_NAME, IBY_PAYMENTS_ALL.PAYEE_ADDRESS_CONCAT, IBY_PAYMENTS_ALL.BENEFICIARY_NAME, IBY_PAYMENTS_ALL.PAYEE_SUPPLIER_SITE_NAME, GL_LEDGERS.NAME, GL_LEDGERS.CURRENCY_CODE, IBY_PAYMENT_METHODS_TL.PAYMENT_METHOD_NAME, FND_LOOKUP_VALUES.MEANING FROM ap_invoice_payments_all INVOICE_PAYMENTS_ALL JOIN ap_invoices_all INVOICES_ALL ON INVOICE_PAYMENTS_ALL.INVOICE_ID = INVOICES_ALL.INVOICE_ID LEFT JOIN ap_checks_all CHECKS_ALL ON INVOICE_PAYMENTS_ALL.CHECK_ID = CHECKS_ALL.CHECK_ID LEFT JOIN ap_payment_schedules_all PAYMENT_SCHEDULES_ALL ON INVOICE_PAYMENTS_ALL.INVOICE_ID = PAYMENT_SCHEDULES_ALL.INVOICE_ID AND INVOICE_PAYMENTS_ALL.PAYMENT_NUM = PAYMENT_SCHEDULES_ALL.PAYMENT_NUM LEFT JOIN ap_lookup_codes LOOKUP_CODES ON LOOKUP_CODES.LOOKUP_TYPE = 'CHECK STATE' AND LOOKUP_CODES.LOOKUP_CODE = CHECKS_ALL.STATUS_LOOKUP_CODE LEFT JOIN ce_payment_documents CE_PAYMENT_DOCUMENTS ON CHECKS_ALL.PAYMENT_DOCUMENT_ID = CE_PAYMENT_DOCUMENTS.PAYMENT_DOCUMENT_ID LEFT JOIN iby_payments_all IBY_PAYMENTS_ALL ON CHECKS_ALL.PAYMENT_ID = IBY_PAYMENTS_ALL.PAYMENT_ID LEFT JOIN ap_terms_tl TERMS_TL ON INVOICES_ALL.TERMS_ID = TERMS_TL.TERM_ID AND COALESCE(TERMS_TL.LANGUAGE, 'US') = 'US' LEFT JOIN gl_ledgers GL_LEDGERS ON GL_LEDGERS.LEDGER_ID = INVOICE_PAYMENTS_ALL.SET_OF_BOOKS_ID LEFT JOIN gl_code_combinations GL_CODE_COMBINATIONS ON GL_CODE_COMBINATIONS.CODE_COMBINATION_ID = INVOICES_ALL.ACCTS_PAY_CODE_COMBINATION_ID LEFT JOIN iby_payment_methods_tl IBY_PAYMENT_METHODS_TL ON IBY_PAYMENTS_ALL.PAYMENT_METHOD_CODE = IBY_PAYMENT_METHODS_TL.PAYMENT_METHOD_CODE AND COALESCE(IBY_PAYMENT_METHODS_TL.LANGUAGE, 'US') = 'US' LEFT JOIN fnd_lookup_values FND_LOOKUP_VALUES ON FND_LOOKUP_VALUES.LOOKUP_TYPE = 'INVOICE TYPE' AND FND_LOOKUP_VALUES.LANGUAGE = 'US' AND INVOICES_ALL.INVOICE_TYPE_LOOKUP_CODE = FND_LOOKUP_VALUES.LOOKUP_CODE WHERE ( INVOICE_PAYMENTS_ALL.last_update_date >= CAST('$LAST_RUN_DATE$' AS DATE) OR CHECKS_ALL.last_update_date >= CAST('$LAST_RUN_DATE$' AS DATE) OR IBY_PAYMENTS_ALL.last_update_date >= CAST('$LAST_RUN_DATE$' AS DATE) OR INVOICES_ALL.last_update_date >= CAST('$LAST_RUN_DATE$' AS DATE) ) ) APPAYMENTS_F_JOIN_A
)
    select * from ct_ap_payments_f_stg;
