{{ config(materialized='table') }}

    with
    gl_periods as (
    select * from {{ ref("gl_periods") }}
),
ct_gl_periods_d_stg as (
    SELECT PERIOD_YEAR || CASE WHEN PERIOD_NUM < 10 THEN '0' || '~' || CAST(PERIOD_NUM AS VARCHAR) ELSE CAST(PERIOD_NUM AS VARCHAR) END AS PERIOD_ID, PERIOD_NAME, PERIOD_SET_NAME, START_DATE AS START_DT, END_DATE AS END_DT, YEAR_START_DATE AS YEAR_START_DT, QUARTER_START_DATE AS QUARTER_START_DT, PERIOD_TYPE, PERIOD_YEAR, PERIOD_NUM, QUARTER_NUM, 'Q' || QUARTER_NUM || '-' || PERIOD_YEAR AS QUARTER_NAME, ENTERED_PERIOD_NAME, ADJUSTMENT_PERIOD_FLAG, DESCRIPTION, CREATION_DATE AS CREATION_DT, CREATED_BY, LAST_UPDATE_DATE AS LAST_UPDATE_DT, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, PERIOD_NAME || '~' || PERIOD_SET_NAME AS INTEGRATION_ID, 1000 AS DATASOURCE_NUM_ID, CASE WHEN SUBSTRING(PERIOD_NAME, 1, 3) IN ('JAN', 'APR', 'JUL', 'OCT') THEN 1 WHEN SUBSTRING(PERIOD_NAME, 1, 3) IN ('FEB', 'MAY', 'AUG', 'NOV') THEN 2 WHEN SUBSTRING(PERIOD_NAME, 1, 3) IN ('MAR', 'JUN', 'SEP', 'DEC') THEN 3 END AS QUARTER_PERIOD_NUM, CASE WHEN QUARTER_NUM = '4' THEN 'Q3-' || CAST(PERIOD_YEAR AS VARCHAR) WHEN QUARTER_NUM = '3' THEN 'Q2-' || CAST(PERIOD_YEAR AS VARCHAR) WHEN QUARTER_NUM = '2' THEN 'Q1-' || CAST(PERIOD_YEAR AS VARCHAR) WHEN QUARTER_NUM = '1' THEN 'Q4-' || CAST(PERIOD_YEAR - 1 AS VARCHAR) END AS PREVIOUS_QUARTER FROM gl_periods
)
    select * from ct_gl_periods_d_stg;
