{{ config(materialized='table') }}

    with
    xle_entity_profiles as (
    select * from {{ ref("xle_entity_profiles") }}
),
xle_registrations as (
    select * from {{ ref("xle_registrations") }}
),
hz_locations as (
    select * from {{ ref("hz_locations") }}
),
ct_legal_entity_d_stg as (
    SELECT XLE_ENTITY_PROFILES.LEGAL_ENTITY_ID AS LEGAL_ENTITY_ID, XLE_ENTITY_PROFILES.LEGAL_ENTITY_IDENTIFIER AS LEGAL_ENITY_NUM, XLE_ENTITY_PROFILES.NAME AS LEGAL_ENTITY_NAME, HZ_LOCATIONS.LOCATION_ID AS LOCATION_ID, HZ_LOCATIONS.COUNTRY AS COUNTRY, HZ_LOCATIONS.ADDRESS1 AS ADDRESS1, HZ_LOCATIONS.ADDRESS2 AS ADDRESS2, HZ_LOCATIONS.ADDRESS3 AS ADDRESS3, HZ_LOCATIONS.ADDRESS4 AS ADDRESS4, HZ_LOCATIONS.CITY AS CITY, HZ_LOCATIONS.POSTAL_CODE AS POSTAL_CODE, HZ_LOCATIONS.STATE AS STATE, HZ_LOCATIONS.PROVINCE AS PROVINCE, HZ_LOCATIONS.COUNTY AS COUNTY, XLE_ENTITY_PROFILES.LAST_UPDATED_BY AS LAST_UPDATED_BY, XLE_ENTITY_PROFILES.CREATION_DATE AS CREATION_DT, XLE_ENTITY_PROFILES.LAST_UPDATE_DATE AS LAST_UPDATE_DT, XLE_ENTITY_PROFILES.CREATED_BY AS CREATED_BY, CAST( XLE_ENTITY_PROFILES.LEGAL_ENTITY_ID AS VARCHAR ) AS INTEGRATION_ID, 1000 AS DATASOURCE_NUM_ID FROM xle_entity_profiles XLE_ENTITY_PROFILES LEFT JOIN xle_registrations XLE_REGISTRATIONS ON XLE_ENTITY_PROFILES.LEGAL_ENTITY_ID = XLE_REGISTRATIONS.SOURCE_ID AND XLE_REGISTRATIONS.SOURCE_TABLE = 'XLE_ENTITY_PROFILES' AND XLE_REGISTRATIONS.IDENTIFYING_FLAG = 'Y' LEFT JOIN hz_locations HZ_LOCATIONS ON XLE_ENTITY_PROFILES.GEOGRAPHY_ID = HZ_LOCATIONS.LOCATION_ID WHERE 1 = 1
)
    select * from ct_legal_entity_d_stg
