{{ config(materialized='table') }}

    with
    org_organization_definitions as (
    select * from {{ ref("org_organization_definitions") }}
),
hr_all_organization_units as (
    select * from {{ ref("hr_all_organization_units") }}
),
xle_entity_profiles as (
    select * from {{ ref("xle_entity_profiles") }}
),
gl_ledgers as (
    select * from {{ ref("gl_ledgers") }}
),
gl_code_combinations as (
    select * from {{ ref("gl_code_combinations") }}
),
hr_locations_all as (
    select * from {{ ref("hr_locations_all") }}
),
fnd_lookup_values as (
    select * from {{ ref("fnd_lookup_values") }}
),
hz_parties as (
    select * from {{ ref("hz_parties") }}
),
ct_org_d_stg as (
    SELECT OOD.ORGANIZATION_ID AS ORG_ID, OOD.ORGANIZATION_NAME AS ORG_NAME, OOD.ORGANIZATION_CODE AS ORG_NUM, HL.DESCRIPTION AS ORG_DESC, HL.ADDRESS_LINE_1 AS ST_ADDRESS1, HL.ADDRESS_LINE_2 AS ST_ADDRESS2, HL.TOWN_OR_CITY AS CITY, HL.COUNTRY AS COUNTY, HL.POSTAL_CODE AS POSTAL_CODE, HL.REGION_1 AS STATE_CODE, HL.REGION_2 AS STATE_NAME, HL.REGION_3 AS STATE_REGION, HL.COUNTRY AS COUNTRY_CODE, FLV_COUNTRY.MEANING AS COUNTRY_NAME, HL.ATTRIBUTE10 AS COUNTRY_REGION, HP.URL AS WEB_ADDRESS, HL.TELEPHONE_NUMBER_1 AS PHONE_NUM, HP.EMAIL_ADDRESS AS EMAIL_ADDRESS, CASE WHEN HAOU.TYPE = 'DIV' THEN 'Y' ELSE 'N' END AS DIVN_FLAG, CASE WHEN HAOU.TYPE = 'BU' THEN 'Y' ELSE 'N' END AS BU_FLAG, CASE WHEN HAOU.TYPE = 'OU' THEN 'Y' ELSE 'N' END AS OPERATING_UNIT_FLAG, XEP.NAME AS LEGAL_ENTITY, CASE WHEN OOD.DISABLE_DATE IS NULL THEN 'Active' ELSE 'Inactive' END AS STATUS, GCC.SEGMENT1 AS COST_CENTER_CODE, HAOU.DATE_FROM AS EFFECTIVE_START_DT, HAOU.DATE_TO AS EFFECTIVE_END_DT, 'Y' AS CURRENT_FLAG, HAOU.CREATION_DATE AS CREATION_DT, HAOU.LAST_UPDATE_DATE AS LAST_UPDATE_DT, HAOU.CREATED_BY AS CREATED_BY, HAOU.LAST_UPDATED_BY AS LAST_UPDATED_BY, CAST(OOD.ORGANIZATION_ID AS VARCHAR) AS INTEGRATION_ID, 1000 AS DATASOURCE_NUM_ID FROM org_organization_definitions OOD INNER JOIN hr_all_organization_units HAOU ON HAOU.ORGANIZATION_ID = OOD.OPERATING_UNIT INNER JOIN xle_entity_profiles XEP ON XEP.LEGAL_ENTITY_ID = OOD.LEGAL_ENTITY INNER JOIN gl_ledgers GLE ON GLE.LEDGER_ID = OOD.SET_OF_BOOKS_ID INNER JOIN gl_code_combinations GCC ON GLE.RET_EARN_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID LEFT JOIN hr_locations_all HL ON HAOU.LOCATION_ID = HL.LOCATION_ID LEFT JOIN fnd_lookup_values FLV_COUNTRY ON HL.COUNTRY = FLV_COUNTRY.LOOKUP_CODE AND FLV_COUNTRY.LOOKUP_TYPE = 'GHR_US_POSTAL_COUNTRY_CODE' LEFT JOIN ( staging.HR_ORGANIZATION_INFORMATION HOI INNER JOIN hz_parties HP ON HOI.PARTY_ID = HP.PARTY_ID AND HOI.ORG_INFORMATION_CONTEXT = 'Operating Unit Information' ) ON HOI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
)
    select * from ct_org_d_stg
